// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnyY4zhULo6pfdpC9ZNEJLT4CbqUO_9SM',
    appId: '1:166916010065:web:a947f59e6172fa47f14870',
    messagingSenderId: '166916010065',
    projectId: 'pesa-planner',
    authDomain: 'pesa-planner.firebaseapp.com',
    storageBucket: 'pesa-planner.firebasestorage.app',
    measurementId: 'G-LP8LPVBDDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5URLMAek0XEWQEPHzZuC_YkTZWEZORGA',
    appId: '1:166916010065:android:30dc2487044497e2f14870',
    messagingSenderId: '166916010065',
    projectId: 'pesa-planner',
    storageBucket: 'pesa-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRdG1W-mRaYDRTAQDnKeFbcrVq5W9n_1Y',
    appId: '1:166916010065:ios:a477133bfe6c848cf14870',
    messagingSenderId: '166916010065',
    projectId: 'pesa-planner',
    storageBucket: 'pesa-planner.firebasestorage.app',
    iosBundleId: 'com.example.pesaPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRdG1W-mRaYDRTAQDnKeFbcrVq5W9n_1Y',
    appId: '1:166916010065:ios:a477133bfe6c848cf14870',
    messagingSenderId: '166916010065',
    projectId: 'pesa-planner',
    storageBucket: 'pesa-planner.firebasestorage.app',
    iosBundleId: 'com.example.pesaPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnyY4zhULo6pfdpC9ZNEJLT4CbqUO_9SM',
    appId: '1:166916010065:web:156a4c36cd2cbdf0f14870',
    messagingSenderId: '166916010065',
    projectId: 'pesa-planner',
    authDomain: 'pesa-planner.firebaseapp.com',
    storageBucket: 'pesa-planner.firebasestorage.app',
    measurementId: 'G-CB9F5586SF',
  );
}
